exporter:
  address: "0.0.0.0:8080"
  log:
    level: "DEBUG"
    format: "json"
  config:
    scrape:
      interval: "60s"
      timeout: "5s"
    quotas:
      - serviceCode: "ec2"
        quotaCode: "L-0263D0A3"
    metrics:
      - name: "route53_hosted_zone_records"
        help: "Number of resource sets in hosted zone"
        script: "aws route53 list-hosted-zones | jq -r \\'.HostedZones[] | \\\"id=\\(.Id),name=\\(.Name),private=\\(.Config.PrivateZone),\\(.ResourceRecordSetCount)\\\"\\'"
