linters:
  enable:
    - megacheck
    - gofmt
    - govet
    - revive # replacement for golint

linters-settings:
  staticcheck:
    checks:
      - '-SA5008'
  gofmt:
    # simplify code: gofmt with `-s` option, true by default
    simplify: true