repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: detect-aws-credentials
        args: ['--allow-missing-credentials']
      - id: detect-private-key
      - id: end-of-file-fixer

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.57.1
    hooks:
      - id: golangci-lint
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.13.1
    hooks:
      - id: helm-docs
        args:
          - --chart-search-root=charts
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.23
    hooks:
      - id: helmlint
