{{- if .Values.exporter.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aws-service-quotas-exporter.configMapName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "aws-service-quotas-exporter.labels" . | nindent 4 }}
data:
  scrape.yaml: |
    {{- toYaml .Values.exporter.config  | nindent 4 }}
{{- end }}
