apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-cfg" (include "aws-service-quotas-exporter.fullname" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "aws-service-quotas-exporter.labels" . | nindent 4 }}
data:
  scrape.yaml: |
    {{- .Values.exporter.config | toYaml | nindent 4 }}
