name: Unit test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

env:
  GO_VERSION: '1.22.0'

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  go:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Get dependencies
        run: |
          go get -v -t -d ./...
      - name: Test
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go test -v ./...
